[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = 'textshape'
version = "1.0.0"
requires-python = ">= 3.10"
dependencies = [
    "numpy>=2.0.0",
    "vharfbuzz>=0.3.1"
]

[tool.mypy]
strict = true
exclude = ["tests/"]
disable_error_code = ["import-untyped"]

[tool.setuptools.packages.find]
include = ["textshape"]

[tool.tox.env_run_base]
deps = ["pytest"]
commands = [["pytest", "-vv", "tests/"]]

[tool.tox.env.type]
deps = ["mypy"]
commands = [["mypy", "."]]

[tool.tox.gh.python]
"3.13" = ["3.13", "type"]
"3.12" = ["3.12"]
"3.11" = ["3.11"]
"3.10" = ["3.10"]